def node_require(script)
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve('#{script}', {paths: [process.argv[1]]})", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')

platform :ios, '15.5'
prepare_react_native_project!

# Fix for duplicate UUIDs
install! 'cocoapods', :deterministic_uuids => false

target 'ShopReserve' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true
  )

  post_install do |installer|
    # Set ONLY_ACTIVE_ARCH to NO at project level (matching simpliride-driver)
    installer.pods_project.build_configurations.each do |config|
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      config.build_settings['SWIFT_ENABLE_EXPLICIT_MODULES'] = 'NO'
    end

    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        build_config.build_settings['SWIFT_VERSION'] = '5.0'
        build_config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        build_config.build_settings['SWIFT_ENABLE_EXPLICIT_MODULES'] = 'NO'

        # Fix deployment target warnings
        if build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 13.0
          build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
      end
    end

    xcconfig_fix = "\nSWIFT_ENABLE_EXPLICIT_MODULES = NO\n"
    Dir.glob(File.join(installer.sandbox.root, 'Target Support Files', '**', '*.xcconfig')).each do |xcconfig_path|
      xcconfig_content = File.read(xcconfig_path)
      unless xcconfig_content.include?('SWIFT_ENABLE_EXPLICIT_MODULES')
        File.open(xcconfig_path, 'a') { |f| f.puts xcconfig_fix }
      end
    end
  end
end
